#!/bin/sh
#

start() {
	echo -n "Starting rescue interfaces... "
	ifup -i /etc/dgprescue/interfaces -a
	echo "Done"
}

stop() {
	echo -n "Stopping rescue interfaces... "
	ifdown -i /etc/dgprescue/interfaces -a
	echo "Done"
}

case "$1" in
  start)
  	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
