#!/bin/sh
#

UMTPRD_DAEMON_NAME=uMTPrd
UMTPRD_DAEMON_PATH=/usr/sbin/umtprd
UMTPRD_DAEMON_PID=/var/run/umtprd.pid

DGPRMTPFW_DAEMON_NAME=dgprescue_mtp_fw
DGPRMTPFW_DAEMON_PATH=/usr/sbin/dgprescue_mtp_fw.sh
DGPRMTPFW_DAEMON_PID=/var/run/dgprescue_mtp_fw.pid

DGPRMTPCMD_DAEMON_NAME=dgprescue_mtp_cmd
DGPRMTPCMD_DAEMON_PATH=/usr/sbin/dgprescue_mtp_cmd.sh
DGPRMTPCMD_DAEMON_PID=/var/run/dgprescue_mtp_cmd.pid

start() {
	echo -n "Starting rescue MTP gadget... "
	gt load -o --file /etc/gadget-tool/mtp mtp
	mkdir -p /run/umtprd/ffs-mtp
	mount -t functionfs mtp /run/umtprd/ffs-mtp/

	# Create cmd directory
	mkdir -p /run/dgprescue/cmd/

	# Create a 32MB tmpfs
	mkdir -p /run/dgprescue/fw/
	mount -t tmpfs -osize=33816576 fw /run/dgprescue/fw/
	# Populate volumes
	for VOL in /sys/class/ubi/ubi0_*; do
		VOLNAME=`cat $VOL/name`
		mkdir /run/dgprescue/fw/$VOLNAME
	done

	start-stop-daemon -S --background \
			  --name $UMTPRD_DAEMON_NAME \
			  -p $UMTPRD_DAEMON_PID -m \
			  --exec /bin/sh -- -c \
			  "$UMTPRD_DAEMON_PATH | logger"

	sleep 5
	echo musb-hdrc.0.auto > /sys/kernel/config/usb_gadget/mtp/UDC
	sleep 5

	start-stop-daemon -S --background \
			  --name $DGPRMTPFW_DAEMON_NAME \
			  -p $DGPRMTPFW_DAEMON_PID -m \
			  --exec /bin/sh -- -c \
			  "$DGPRMTPFW_DAEMON_PATH | logger"

	start-stop-daemon -S --background \
			  --name $DGPRMTPCMD_DAEMON_NAME \
			  -p $DGPRMTPCMD_DAEMON_PID -m \
			  --exec /bin/sh -- -c \
			  "$DGPRMTPCMD_DAEMON_PATH | logger"

	echo "Done"
}

stop() {
	echo -n "Stopping rescue MTP gadget... "
	echo "Done"
}

case "$1" in
  start)
  	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
